# Generated by Django 3.2.9 on 2024-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='invite_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default=('pending', 'Pending'), max_length=10),
        ),
    ]
