# Generated by Django 3.2.9 on 2024-08-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0003_alter_userrequest_invite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='invite_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
