import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/userContext";
import { AttendanceProvider } from "./context/attendaceContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <UserProvider >
          <AttendanceProvider>
          {children}
          </AttendanceProvider>
        </UserProvider>
      </body>
    </html>
  );
}
