# Generated by Django 3.2.9 on 2024-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0003_auto_20240803_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
