# Generated by Django 3.2.9 on 2024-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockin', '0004_alter_attendance_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True),
        ),
    ]
